.v q0 q1 q2 q3 q4

BEGIN
H q0
T q1
Tof q3 q0
Tof q1 q2
T q4
Tof q2 q4
H q3
T q2
Tof q2 q4
H q3
T q0
H q2
T q3
Tof q4 q0
Tof q4 q3
Tof q4 q0
T q4
T q1
T q2
Tof q2 q0
T q0
Tof q4 q2
H q2
H q2
T q4
Tof q2 q3
Tof q0 q3
H q4
T q3
T q4
Tof q0 q3
Tof q0 q2
H q0
T q4
Tof q4 q1
Tof q4 q0
Tof q3 q0
T q1
T q2
T q2
T q1
T q4
T q0
T q1
H q0
H q4
H q2
Tof q4 q3
Tof q0 q4
T q1
Tof q1 q3
Tof q2 q3
Tof q1 q4
Tof q3 q4
Tof q3 q2
T q0
H q1
H q3
Tof q2 q4
END
