.v q0 q1 q2 q3 q4 q5 q6 q7

BEGIN
Tof q6 q7
Tof q5 q0
H q6
T q5
T q4
H q3
Tof q6 q4
Tof q7 q4
T q6
T q3
T q1
T q3
Tof q7 q0
T q5
T q3
Tof q0 q4
Tof q1 q4
T q5
T q4
Tof q3 q6
Tof q2 q1
H q1
Tof q4 q5
Tof q3 q5
Tof q3 q4
H q2
H q3
T q7
Tof q1 q3
T q7
Tof q2 q5
Tof q0 q2
Tof q2 q7
Tof q0 q2
T q0
Tof q2 q0
Tof q5 q4
H q1
H q1
T q4
T q1
Tof q0 q6
T q3
Tof q6 q2
Tof q2 q5
Tof q7 q3
Tof q0 q7
Tof q2 q3
Tof q5 q0
T q0
Tof q1 q3
Tof q1 q2
H q3
END
